Add first pass at linter
oalders/ppath pull request #1
Opened 2022-10-17 21:37 UTC by oalders

2022-10-25 20:58 UTC, PatrickCronin requested changes
Looks very nice! I made a few recommendations for improvements.

2022-10-25 20:58 UTC, PatrickCronin commented on audit/audit.go
> +				ok, err := patternsOk(&seen, ignoreConfig, commandName, section, list)
If dereferencing `seen` is to avoid copying it, a map is a reference type in go, so there'd be no copying going on if you just passed `seen` without the `&`.

2022-10-25 20:58 UTC, PatrickCronin commented on audit/audit.go
> +func patternsOk(seen *matchCache, ppath *Ppath, commandName, section string, patterns []string) (bool, error) {
I don't see the advantage of using a pointer to a matchCache in this method. I think a plain matchCache would be fine.

2022-10-25 20:58 UTC, PatrickCronin commented on audit/audit.go
> +		// For our purposes found and ignored are the same thing.
I appreciated this comment.

2022-10-25 20:58 UTC, PatrickCronin commented on audit/audit.go
> +			}
It seems weird to me that this block is above the `if err != nil` block. If you switched them, you could get rid of the `err == nil` part in this one.

2022-10-25 20:58 UTC, PatrickCronin commented on audit/audit.go
> +						err,
Since this err is coming from an external library, you might consider wrapping it with something that will include a stack trace.

2022-10-25 20:58 UTC, PatrickCronin commented on audit/config.go
> +			"error reading ppath config file %s: %w", filename, err,
Consider wrapping the error with a stack trace.

2022-10-25 20:58 UTC, PatrickCronin commented on audit/config.go
> +	}
I think you would want to explicitly check this error with `os.IsNotExist(err)`. If that's true, feel free to return the empty config, but if it's not true, then I think you'd want to return the (wrapped with stack trace) err.

2022-10-25 20:58 UTC, PatrickCronin commented on audit/config.go
> +		log.Fatalf("unmarshal %v", err)
I believe some code bases are concerned with programs exiting not from main; you might consider returning the err and allowing main to do the logging/fataling.

2022-10-25 20:58 UTC, PatrickCronin commented on audit/config.go
> +			"error reading precious config file %s: %w", filename, err,
Consider wrapping the err with a stack trace.

2022-10-25 20:58 UTC, PatrickCronin commented on audit/config.go
> +		log.Fatalf("unmarshal %v", err)
Perhaps consider returning (wrapped) err here.

2022-10-25 20:58 UTC, PatrickCronin commented on audit/config_test.go
> +	)
This could be a single assert.Equal, but it's fine that it isn't.

2022-10-25 20:58 UTC, PatrickCronin commented on audit/config_test.go
> +	)
This could be a single assert.Equal, but it's fine that it isn't.

2022-10-25 20:58 UTC, PatrickCronin commented on audit/config_test.go
> +	)
This could be a single assert.Equal, but it's fine that it isn't.

2022-10-27 12:33 UTC, PatrickCronin reviewed
Looks like one thing was left from the previous review, and I've made a new comment. FWIW I don't have a "resolve" button so feel free to resolve whatever you'd like.

2022-10-27 14:56 UTC, oalders commented on audit/config.go
> +		log.Fatalf("unmarshal %v", err)
Thanks! I had forgotten to commit that. Just force-pushed it.

2022-10-27 15:09 UTC, oalders commented on audit/audit.go
> +				if !errors.Is(err, os.ErrNotExist) {
It actually returns `os.ErrNotExist` on the pattern `foo`, so I think making this something that exits the code would not be helpful.

2022-10-27 15:21 UTC, oalders commented on audit/audit.go
> +				if !errors.Is(err, os.ErrNotExist) {
To follow up, it looks like this error is returned in the case where you provide something that is not a glob pattern but is not found on the file system. So, I think the handling is correct. This allows us to have `zglob` look for both patterns and file names.

2022-10-27 15:22 UTC, PatrickCronin approved these changes
Looks great! 👏

2022-10-27 15:32 UTC, merged